[tasks.build]
command = "cargo"
args = ["build"]

[tasks.xephyr]
dependencies = ["build"]
script = [
    "Xephyr :2 -screen 1680x1050 -dpi 96 &",
    "sleep 1",
    "rm -f *.log",
    "(DISPLAY=:2 RUST_BACKTRACE=1 ../ceramic/target/debug/ceramic >ceramic.log 2>ceramic.err.log ; echo 'Finished Ceramic' >>ceramic.log) &",
    "(DISPLAY=:2 RUST_BACKTRACE=1 ../commando/target/debug/commando -vvv >commando.log 2>commando.err.log ; echo 'Finished Commando' >>commando.log) &",
    "sleep 2",
    "DISPLAY=:2 nitrogen --set-scaled ~/.config/wallpaper/rsmith_single_blade_of_grass.jpg &",
    "DISPLAY=:2 MONITOR=default polybar --reload top &",
    "DISPLAY=:2 rxvt &",
    "DISPLAY=:2 rxvt &",
    "DISPLAY=:2 rxvt &",
    "tail -fqF *.log"
]

[tasks.vnc]
dependencies = ["build"]
script = [
    "tigervncserver :2 -localhost no --I-KNOW-THIS-IS-INSECURE -fg -cleanstale -geometry 2560x1440 -depth 24 -dpi 96 -rfbport 5911 -SecurityTypes None -AllowOverride RemapKeys -xstartup ./xstartup",
]