#!/usr/bin/env zsh

if [ -e "$HOME/.Xresources" ] ; then
    xrdb "$HOME/.Xresources"
fi

xmodmap -e 'keycode any = Hyper_L'
xmodmap -e 'keycode any = Hyper_R'

xmodmap -e 'remove mod4 = Hyper_L'
xmodmap -e 'remove mod4 = Hyper_R'
xmodmap -e 'add mod3 = Hyper_L'
xmodmap -e 'add mod3 = Hyper_R'

tigervncconfig -nowin & # Handles C/C/P

nitrogen --random --set-scaled $HOME/.config/wallpaper &
../ceramic/target/debug/ceramic &
(sleep 4 ; ~/.config/polybar/launch.sh ) &
(sleep 4 ; lxterminal & ) &
(sleep 4 ; lxterminal & ) &
(sleep 4 ; lxterminal & ) &
RUST_BACKTRACE=1 target/debug/commando -vvv